Application/OkanDemir.WebUI.Cms/Controllers/IncomeController.cs
using OkanDemir.WebUI.Cms.Authorize;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using OkanDemir.Business;
using OkanDemir.WebUI.Cms.Helpers;
using OkanDemir.Business.Filters;
using OkanDemir.Dto;
using System.Diagnostics;

namespace OkanDemir.WebUI.Cms.Controllers
{
    [Authorize]
    public class IncomeController : Controller
    {
        IncomeBusiness _incomeBusiness;

        public IncomeController(IncomeBusiness _incomeBusiness)
        {
            this._incomeBusiness = _incomeBusiness;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetList(DataTableParameters dataTableParameters)
        {
            dataTableParameters.UserId = User.GetUserId();
            var response = _incomeBusiness.GetAll(new IncomeFilterModel(dataTableParameters));

            return Json(
            new
            {
                draw = dataTableParameters.Draw,
                recordsFiltered = response.RecordsFiltered,
                recordsTotal = response.TotalCount,
                data = response.Data
            });
        }

        public IActionResult Create()
        {
            return View(new IncomeDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(IncomeDto model, IFormFile file)
        {
            if (file != null)
            {
                var fileResponse = ImageHelper.UploadFile("income", file);
                model.FilePath = fileResponse.Path;
            }

            var response = _incomeBusiness.Create(model);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }

        public IActionResult Edit(int id)
        {
            var data = _incomeBusiness.Get(User.GetUserId(), id);
            if (data == null)
                return RedirectToAction("Index", "Income", new { q = "not_found_data" });

            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IncomeDto model, IFormFile file)
        {
            if (file != null)
            {
                var fileResponse = ImageHelper.UploadFile("income", file);
                model.FilePath = fileResponse.Path;
            }

            var response = _incomeBusiness.Update(model);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var response = _incomeBusiness.Delete(User.GetUserId(), id);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }

        [HttpGet]
        public JsonResult Active(int id)
        {
            var response = _incomeBusiness.Payment(User.GetUserId(), id);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }

        [HttpGet]
        public JsonResult Passive(int id)
        {
            var response = _incomeBusiness.UnPayment(User.GetUserId(), id);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }
    }
}

Application/OkanDemir.WebUI.Cms/Views/Income/Components/IncomeForm/IncomeFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OkanDemir.Business;
using OkanDemir.Dto;
using OkanDemir.WebUI.Cms.Helpers;

namespace OkanDemir.WebUI.Cms.Views.Income.Components.IncomeForm
{
    public class IncomeFormViewComponent : ViewComponent
    {
        IncomeTypeBusiness incomeTypeBusiness;
        public IncomeFormViewComponent(IncomeTypeBusiness incomeTypeBusiness)
        {
            this.incomeTypeBusiness = incomeTypeBusiness;
        }

        public IViewComponentResult Invoke(string action,
            IncomeDto model)
        {
            ViewBag.Action = action;
            ViewBag.Categories = incomeTypeBusiness.GetAllActiveList(User.GetUserId());
            return View(model);
        }

    }
}

Application/OkanDemir.WebUI.Cms/Views/Income/Create.cshtml
@model IncomeDto

@{
    var title = "Gelir Ekle";
    ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
    new List<Bc>() {
        new Bc("Dashboard", Url.Action("Index","Home")),
        new Bc("Liste", Url.Action("Index","Income")),
        new Bc(title , "")
    }
))

@Html.Raw(pageHeader.MainHeader(
    title,
    "",
    "Listeye Dön",
    Url.Action("Index","Income")
))

<div class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@title</h5>
                </div>
                <div class="card-body">
                    @await Component.InvokeAsync("IncomeForm", new { action = "Create", Model = new IncomeDto() })
                </div>
            </div>
        </div>
    </div>
</div>
 
@section Styles
{
  @await Html.PartialAsync("Components/IncomeForm/_IncomeFormStylesPartial") 
}

@section Scripts
{
  @await Html.PartialAsync("Components/IncomeForm/_IncomeFormScriptsPartial")
}

Application/OkanDemir.WebUI.Cms/Views/Income/Edit.cshtml
@model IncomeDto

@{
    var title = "Gelir Düzenle";
    ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
    new List<Bc>() {
        new Bc("Dashboard", Url.Action("Index","Home")),
        new Bc("Liste", Url.Action("Index","Income")),
        new Bc(title , "")
    }
))

@Html.Raw(pageHeader.MainHeader(
    title,
    "",
    "Listeye Dön",
    Url.Action("Index","Income")
))


<div class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@title</h5>
                </div>
                <div class="card-body">
                    @await Component.InvokeAsync("IncomeForm", new { action = "Edit", Model = Model })
                </div>
            </div>
        </div>
    </div>
</div>
 
 

@section Styles
    {
    @await Html.PartialAsync("Components/IncomeForm/_IncomeFormStylesPartial")
}

    @section Scripts
    {
    @await Html.PartialAsync("Components/IncomeForm/_IncomeFormScriptsPartial")
}

Application/OkanDemir.WebUI.Cms/Views/Income/Index.cshtml
@{
    var title = "Gelir Listesi";
    ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
    new List<Bc>() {
        new Bc("Dashboard", Url.Action("Index","Home")),
        new Bc("Gelirler" , "")
    }
))

@Html.Raw(pageHeader.MainHeader(
    title,
    "",
    "Yeni Ekle",
    Url.Action("Create","Income")
))


<div class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@title</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-10 mb-3">
                            <input placeholder="Ara..." class="form-control" id="contentSearchInput">
                        </div>
                        <div class="col-2 mb-3">
                            <button class="btn btn-success" id="filterButton">Filtrele</button>
                        </div>
                        <div class="col-12">
                            <span class="text-muted text-small datatable-outofbox-infotext"> </span>
                            <button class="btn btn-outline-dark btn-xs dropdown-toggle datatable-outofbox-lengthtext" type="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                10
                            </button>
                            <div class="dropdown-menu dropdown-menu-right datatable-outofbox-length">
                                <a class="dropdown-item datatable-outofbox-dropdownButton">10</a>
                                <a class="dropdown-item datatable-outofbox-dropdownButton">20</a>
                                <a class="dropdown-item datatable-outofbox-dropdownButton">30</a>
                                <a class="dropdown-item datatable-outofbox-dropdownButton">50</a>
                                <a class="dropdown-item datatable-outofbox-dropdownButton">100</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive px-2 border-0">
                    <table class="table table-bordered table-hover table-striped" id="contentDataTable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Başlık</th>
                                <th>Ödendi Mi?</th>
                                <th>-</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        var oTable;
        $(document).ready(function () {
            oTable = main.CreateDatatable('#contentDataTable',
            {
                serverSide: true,
                ajax: {
                    url: "@Url.Action("GetList", "Income")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                    },
                },
                "columns": [
                    { "data": "id", "name": "Id", "autoWidth": true },
                    { "data": "incomeTypeName", "name": "IncomeTypeName", "autoWidth": true },
                    {
                        "data": "id", "name": "Id", "autoWidth": true,
                        "render": function (data, type, full, meta) {
                            var retHtml = "";
                            if(full.hasPayment){
                                retHtml += '<span class="badge bg-success passive" data-id="'+full.id+'">Ödendi</span>';
                            }
                            else{
                                retHtml += '<span class="badge bg-danger active" data-id="' + full.id + '">Ödenmedi</span>';
                            }
                            return retHtml;
                        }
                    },
                    {
                        "data": "id", "name": "Id", "autoWidth": true,
                        "render": function (data, type, full, meta) {
                            var retHtml = "";
                            retHtml += '<a class="badge bg-primary me-2" href="/Income/Edit/' + full.id + '">Düzenle</a>';
                            retHtml += '<a class="badge bg-danger delete" data-id="' + full.id + '">Sil</a>';
                            return retHtml;
                        }
                    },
                ]
            });

            $("body").on("click", "#filterButton", function () {
                oTable.search($("#contentSearchInput").val());
                oTable.draw();
            });

            $('body').keypress(function (event) {
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if (keycode == '13') {
                    event.preventDefault();
                }
            });

            $('#contentSearchInput').keypress(function (event) {
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if (keycode == '13') {
                    oTable.search($("#contentSearchInput").val());
                    oTable.draw();
                }
            });

            $("body").on("click", ".delete", function () {
                var id = $(this).attr("data-id");
                layoutJsHelper.deleteItem("Income", id);
            });

            $("body").on("click", ".passive", function () {
                var id = $(this).attr("data-id");
                layoutJsHelper.passive("Income", id);
            });

            $("body").on("click", ".active", function () {
                var id = $(this).attr("data-id");
                layoutJsHelper.active("Income", id);
            });
        });
    </script>
}