Application/OkanDemir.WebUI.Cms/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using OkanDemir.Business;
using OkanDemir.Dto;
using OkanDemir.WebUI.Cms.Authorize;
using OkanDemir.WebUI.Cms.Helpers;
using OkanDemir.WebUI.Cms.Models;

namespace OkanDemir.WebUI.Cms.Controllers
{
    [Authorize]
    public class TodoController : Controller
    {
        TodoBusiness _todoBusiness;
        CacheHelper _cache;

        public TodoController(TodoBusiness _todoBusiness, CacheHelper _cache)
        {
            this._todoBusiness = _todoBusiness;
            this._cache = _cache;
        }

        [HttpGet]
        public IActionResult Index(int projectId)
        {
            var tables = _todoBusiness.GetAllTodoTables(User.GetUserId(), projectId);
            var todos = _todoBusiness.GetAllTodoList(User.GetUserId(), projectId);
            var types = _todoBusiness.GetTodoListTypes();

            var model = new TodoViewModel()
            {
                TodoLists = todos,
                TodoListTypes = types,
                TodoTables = tables,
            };

            return View(model);
        }
    }
}

Application/OkanDemir.WebUI.Cms/Controllers/TodoProjectController.cs
using Microsoft.AspNetCore.Mvc;
using OkanDemir.Business;
using OkanDemir.Dto;
using OkanDemir.WebUI.Cms.Authorize;
using OkanDemir.WebUI.Cms.Helpers;

namespace OkanDemir.WebUI.Cms.Controllers
{
    [Authorize]
    public class TodoProjectController : Controller
    {
        TodoProjectBusiness _todoBusiness;
        CacheHelper _cache;

        public TodoProjectController(TodoProjectBusiness _todoBusiness, CacheHelper _cache)
        {
            this._todoBusiness = _todoBusiness;
            this._cache = _cache;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = _todoBusiness.GetAllTodoProjectsList(User.GetUserId());
            return View(list);
        }
        

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TodoProjectDto model)
        {
            var response = _todoBusiness.ProjectCreate(model);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }

        public IActionResult Edit(int id)
        {
            var data = _todoBusiness.ProjectGet(User.GetUserId(), id);
            if (data == null)
                return RedirectToAction("Index", "ArchiveCategory", new { q = "not_found_data" });

            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TodoProjectDto model)
        {
            var response = _todoBusiness.ProjectUpdate(model);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var response = _todoBusiness.ProjectDelete(User.GetUserId(), id);
            return Json(new { isSucceed = response.IsSucceed, message = response.Message, errors = response.Errors });
        }
    }
}

Application/OkanDemir.WebUI.Cms/Views/TodoProject/Components/TodoProjectForm/TodoProjectFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OkanDemir.Dto;

namespace OkanDemir.WebUI.Cms.Views.TodoProject.Components.TodoProjectForm
{
    public class TodoProjectFormViewComponent : ViewComponent
    {
        
        public IViewComponentResult Invoke(string action,
            TodoProjectDto model)
        {
            ViewBag.Action = action;
            return View(model);
        }

    }
}

Application/OkanDemir.WebUI.Cms/Views/TodoProject/Create.cshtml
@model TodoProjectDto

@{
    var title = "Todo Proje Ekle";
    ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
    new List<Bc>() {
        new Bc("Dashboard", Url.Action("Index","Home")),
        new Bc("Liste", Url.Action("Index","TodoProject")),
        new Bc(title , "")
    }
))

@Html.Raw(pageHeader.MainHeader(
    title,
    "",
    "Listeye Dön",
    Url.Action("Index","TodoProject")
))

<div class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@title</h5>
                </div>
                <div class="card-body">
                    @await Component.InvokeAsync("TodoProjectForm", new { action = "Create", Model = new TodoProjectDto() })
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
  @await Html.PartialAsync("Components/TodoProjectForm/_TodoProjectFormScriptsPartial")
}

Application/OkanDemir.WebUI.Cms/Views/TodoProject/Edit.cshtml
@model TodoProjectDto

@{
    var title = "Todo Proje Düzenle";
    ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
    new List<Bc>() {
        new Bc("Dashboard", Url.Action("Index","Home")),
        new Bc("Liste", Url.Action("Index","TodoProject")),
        new Bc(title , "")
    }
))

@Html.Raw(pageHeader.MainHeader(
    title,
    "",
    "Listeye Dön",
    Url.Action("Index","TodoProject")
))


<div class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">@title</h5>
                </div>
                <div class="card-body">
                    @await Component.InvokeAsync("TodoProjectForm", new { action = "Edit", Model = Model })
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    @await Html.PartialAsync("Components/TodoProjectForm/_TodoProjectFormScriptsPartial")
}

Application/OkanDemir.WebUI.Cms/Views/TodoProject/Index.cshtml
@model List<TodoProjectDto>
@{
	var title = "Todo Proje Listesi";
	ViewData["Title"] = title;
}

@Html.Raw(bread.BreadCrumb(
		new List<Bc>() {
		new Bc("Dashboard", Url.Action("Index","Home")),
		new Bc(title , "")
	}
	))

@Html.Raw(pageHeader.MainHeader(
		title,
		"",
		"Yeni Ekle",
		Url.Action("Create", "TodoProject")
	))


<div class="content">
	<div class="row">
		@foreach (var item in Model)
		{
			<div class="col-md-3 col-sm-12">
				<div class="card">
					<div class="card-header border-0 d-flex flex-wrap">
						<h6 class="mb-0">@item.Title</h6>
						<div class="d-inline-flex ms-auto" style="align-items:center;">
							<a class="text-body" href="@Url.Action("Edit","TodoProject", new { id = item.Id })">
								<i class="ph-note-pencil"></i>
							</a>
							<a class="text-body mx-2" href="@Url.Action("Index","Todo", new { projectId = item.Id })">
								<i class="ph-list-checks"></i>
							</a>
							<a class="text-body me-2" href="@Url.Action("Index","Todo", new { projectId = item.Id })">
								<i class="ph-table"></i>
							</a>
							<a class="text-body cursor-pointer delete" data-id="@item.Id">
								<i class="ph-trash"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>


@section scripts {
	<script>
		$(document).ready(function () {
			$("body").on("click", ".delete", function () {
				var id = $(this).attr("data-id");
				layoutJsHelper.deleteItem("TodoProject", id);
			});
		});
	</script>
}